// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIJaMs6rjNFtFrTC-HaCRDg8sQkX67xw',
    appId: '1:862408965455:web:968d69abe0339e63ef193a',
    messagingSenderId: '862408965455',
    projectId: 'whatsapp-e85f4',
    authDomain: 'whatsapp-e85f4.firebaseapp.com',
    storageBucket: 'whatsapp-e85f4.appspot.com',
    measurementId: 'G-KGEJZVRHMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pj8FU4GJt1PpfsKqNj6g2AoVk7WZMUg',
    appId: '1:862408965455:android:29d5278e3e557a68ef193a',
    messagingSenderId: '862408965455',
    projectId: 'whatsapp-e85f4',
    storageBucket: 'whatsapp-e85f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHrxRZB263fegjp7pCNYd6dzltazIE70',
    appId: '1:862408965455:ios:d0d50dfe962b7357ef193a',
    messagingSenderId: '862408965455',
    projectId: 'whatsapp-e85f4',
    storageBucket: 'whatsapp-e85f4.appspot.com',
    iosClientId: '862408965455-4blldmpbmie4gfsbubcpjocrgpg4icbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHrxRZB263fegjp7pCNYd6dzltazIE70',
    appId: '1:862408965455:ios:d0d50dfe962b7357ef193a',
    messagingSenderId: '862408965455',
    projectId: 'whatsapp-e85f4',
    storageBucket: 'whatsapp-e85f4.appspot.com',
    iosClientId: '862408965455-4blldmpbmie4gfsbubcpjocrgpg4icbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
